### ISSUE TITLE
Provide HTTP/2 server example in the website

### ISSUE THREAD

**Issue by n1haldev** [hyperium/hyperium.github.io#137]
Right now, hyper.rs only provides an HTTP/1 server example. It might be a good idea to add an HTTP/2 version.

This issue was raised in the hyper repository as https://github.com/hyperium/hyper/issues/3568
Please assign this issue to me.

**Comment by dswij** [comment]
Let's keep the issues in one place for easier tracking. You can open up a PR (or draft) to this repo if you want to help with the website documentation.
