### ISSUE TITLE
reconsider choice of service_fn for promotional code snippet

### ISSUE THREAD

**Issue by softprops** [hyperium/hyperium.github.io#17]
I consider hyper a defacto standard for http in the rust ecosystem. As such, it's likely going to be one of the first stops for a rust newbie. 

The example code on this site using `service_fn` shows how simple it is to set up a service. However, for those new to rust or even moderately acclimated are going to assume the code in the example is going to be downloadable from crates.io as an officially published crate. I just fell for that trick which required some digging to know that its not and that I needed to depend on it from git source instead. I understand that's not uncommon for experimental crate usage but I feel like hyper is not. To make the experience for first timer rustaceans a pleasant one, I might consider an example that uses only dependencies that are published to crates.io.

**Comment by seanmonstar** [comment]
hyper now has `service_fn` directly in it :D
