### ISSUE TITLE
Links to other guide pages are incorrect.

### ISSUE THREAD

**Issue by jolhoeft** [hyperium/hyperium.github.io#24]
We are using constructs like `[Echo, echo, echo](./echo)` to link to other pages in the guides. That link appears in handle_params.md for example. When viewing the page in github, the relative linking is correct (except there is no trailing `.md`). However, on the guide pages, instead of linking to https://hyper.rs/guides/server/echo/, it is linking to https://hyper.rs/guides/server/handle_post/echo

I don't know what software is generating the guide pages from the markdown, so can't figure out how to fix this.

**Comment by seanmonstar** [comment]
The software is Jekyll, what Github Pages promotes. It might be an error in the liquid templates that generate navigation links, but either way, I'd lean towards the links should be right on the website over them being right in Github's UI.
