### ISSUE TITLE
Getting started With a Client. Example code not working.

### ISSUE THREAD

**Issue by jdoig** [hyperium/hyperium.github.io#26]
It looks like too many lines are commented out in the "full example" here: https://github.com/hyperium/hyperium.github.io/blob/master/_guides/client/basic.md

(e.g the run function declaration, etc)

Resulting in code that wont compile here: https://hyper.rs/guides/client/basic/

**Comment by lePereT** [comment]
yup, this doesn't compile. not the greatest of intros to hyper

**Comment by seanmonstar** [comment]
The guides now link to full examples in the hyper repo, tested to compile with every commit.
