### ISSUE TITLE
hyper.rs link on header should link to home page

### ISSUE THREAD

**Issue by andradei** [hyperium/hyperium.github.io#29]
Right now it is broken, being rendered without an `href`, the pertaining line is not rendering the variable correctly.

https://github.com/hyperium/hyperium.github.io/blob/master/_includes/header.html#L6

**Comment by markhildreth** [comment]
This appears to have been [fixed](https://github.com/hyperium/hyperium.github.io/commit/94f2a58704e81a6530fe628e20d83cdbf256b530#diff-822e9cf54ee310f9a7ebd0d16c9ae066).
