### ISSUE TITLE
Document has an error here

### ISSUE THREAD

**Issue by driftluo** [hyperium/hyperium.github.io#34]
On Advanced Client Usage:
```rust
let (posted, got) = tokio::executor::current_thread::block_on_all(work).unwrap();
```
This code will cause panic `SpawnError { is_shutdown: true }`

relationship: tokio [#337](https://github.com/tokio-rs/tokio/issues/377) 

If you want to get results in the current thread, you should do it like this:

```rust
use tokio::runtime::current_thread::Runtime;

let run_time = Runtime::new()?;
let responses = self.run_time.block_on(work)?;
```

**Comment by markhildreth** [comment]
This appears to have been [changed](https://github.com/hyperium/hyperium.github.io/commit/8b1f6c28f70be2f789958945a40041284d251cb2#diff-d0b21d1054ae3bebcab0f755b61df9b3L132) and fixed. I was able to get the current documentation running, although the documentation was missing some imports to get the advanced code to run. I opened up PR #43 to fix that problem, so the client tutorials should now run without any code changes necessary.
