### ISSUE TITLE
Favicon/icon for hyper suggestion

### ISSUE THREAD

**Issue by Tacklebox** [hyperium/hyperium.github.io#44]
I saw the issue requesting a favicon on hyper, and the subsequent PR here where it was decided to leave the favicon blank until an icon was chosen. I made this from the rust logo. What do you think? ![image](https://user-images.githubusercontent.com/5867784/67076814-c662a580-f142-11e9-8b69-b887553ef5aa.png)

**Comment by seanmonstar** [comment]
Woah, hey, that looks really cool!

Personally I think I'd want to stick with the orange branding hyper has had so far (cc https://github.com/hyperium/hyper/issues/1289).

**Comment by Tacklebox** [comment]
Sure, I don't know what's better, framing the black in orange or having the gear/letter be orange itself. do either of these fit the bill?

![image](https://user-images.githubusercontent.com/5867784/67153942-a00a4a80-f2a7-11e9-88f1-6d39805be998.png)

![image](https://user-images.githubusercontent.com/5867784/67153945-a7c9ef00-f2a7-11e9-9ff8-7e13e7991c94.png)

**Comment by seanmonstar** [comment]
Hm, I may wish for hyper's branding to not be so close to the official Rust branding.

**Comment by sakshatshinde** [comment]
Can I give it a shot as well?
